// ── NARRATIVE TRANSLATIONS ────────────────────────────────────────
// DataShop CEO — all story / narrative content in NL and EN.
// Access via:  n(id, field)  →  returns string in current LANG
// Example:     n('new_customer', 'title')

const NARRATIVE = {

  // ══ SCENARIOS ══════════════════════════════════════════════════
  scenarios: {
    new_customer: {
      nl: { title:'Nieuwe klant registreren', who:'Klantenservice',
            story:'<strong>Sophie Vermeersch</strong> uit <strong>Gent</strong> registreerde zich net. Email: <strong>sophie@mail.be</strong>. Actief account. Voeg toe!',
            obj:'INSERT INTO klant (naam, email, stad, actief) VALUES (...)',
            win:'Sophie staat in de databank! 🎉' },
      en: { title:'Register new customer', who:'Customer Service',
            story:'<strong>Sophie Vermeersch</strong> from <strong>Ghent</strong> just registered. Email: <strong>sophie@mail.be</strong>. Active account. Add her!',
            obj:'INSERT INTO klant (naam, email, stad, actief) VALUES (...)',
            win:'Sophie is in the database! 🎉' },
    },
    price_update: {
      nl: { title:'Prijsaanpassing doorvoeren', who:'Leverancier',
            story:'USB-C Hub (product_id=2) krijgt nieuwe prijs: <strong>€44.99</strong>. Pas aan vóór de webshop opent.',
            obj:'UPDATE product SET prijs = 44.99 WHERE product_id = 2',
            win:'Prijs bijgewerkt. Geen verlies meer. 💶' },
      en: { title:'Apply price update', who:'Supplier',
            story:'USB-C Hub (product_id=2) gets a new price: <strong>€44.99</strong>. Update it before the shop opens.',
            obj:'UPDATE product SET prijs = 44.99 WHERE product_id = 2',
            win:'Price updated. No more losses. 💶' },
    },
    query_gent: {
      nl: { title:'Klanten uit Gent opzoeken', who:'Marketing',
            story:'Marketing lanceert een Gent-campagne. Geef namen en e-mails van klanten uit <strong>Gent</strong>, gesorteerd op naam.',
            obj:'SELECT naam, email FROM klant WHERE stad = \'Gent\' ORDER BY naam',
            win:'Lijst verstuurd! Campagne gelanceerd. 📣' },
      en: { title:'Look up customers from Ghent', who:'Marketing',
            story:'Marketing is launching a Ghent campaign. Get names and emails of customers from <strong>Ghent</strong>, sorted by name.',
            obj:'SELECT naam, email FROM klant WHERE stad = \'Gent\' ORDER BY naam',
            win:'List sent! Campaign launched. 📣' },
    },
    deactivate_gdpr: {
      nl: { title:'GDPR — Account deactiveren', who:'Juridische Dienst',
            story:'<strong>Kobe Janssen</strong> (klant_id=4) vraagt deactivering. GDPR verbiedt verwijdering — zet enkel <strong>actief = 0</strong>.',
            obj:'UPDATE klant SET actief = 0 WHERE klant_id = 4',
            win:'Kobe gedeactiveerd. GDPR correct nageleefd. ✅' },
      en: { title:'GDPR — Deactivate account', who:'Legal Department',
            story:'<strong>Kobe Janssen</strong> (klant_id=4) requests deactivation. GDPR prohibits deletion — just set <strong>actief = 0</strong>.',
            obj:'UPDATE klant SET actief = 0 WHERE klant_id = 4',
            win:'Kobe deactivated. GDPR correctly followed. ✅' },
    },
    new_product: {
      nl: { title:'Nieuw product toevoegen', who:'Inkoop',
            story:'Nieuw product: <strong>Staande Lamp LED</strong>, prijs <strong>€89.99</strong>, stock <strong>10</strong>, categorie <strong>Wonen</strong>.',
            obj:'INSERT INTO product (naam, prijs, stock, categorie) VALUES (\'Staande Lamp LED\', 89.99, 10, \'Wonen\')',
            win:'Staande Lamp LED live! 💡' },
      en: { title:'Add new product', who:'Purchasing',
            story:'New product: <strong>Standing LED Lamp</strong>, price <strong>€89.99</strong>, stock <strong>10</strong>, category <strong>Wonen</strong>.',
            obj:'INSERT INTO product (naam, prijs, stock, categorie) VALUES (\'Staande Lamp LED\', 89.99, 10, \'Wonen\')',
            win:'Standing LED Lamp is live! 💡' },
    },
    active_customers: {
      nl: { title:'Actieve klanten opzoeken', who:'Marketing',
            story:'Haal alle klanten op waarbij <strong>actief = 1</strong>, gesorteerd op naam. Welke zijn er?',
            obj:'SELECT naam, email FROM klant WHERE actief = 1 ORDER BY naam',
            win:'Actieve klantenlijst klaar! Campagne kan starten. 📣' },
      en: { title:'Look up active customers', who:'Marketing',
            story:'Get all customers where <strong>actief = 1</strong>, sorted by name. Who are they?',
            obj:'SELECT naam, email FROM klant WHERE actief = 1 ORDER BY naam',
            win:'Active customer list ready! Campaign can start. 📣' },
    },
    count_products: {
      nl: { title:'Hoeveel producten?', who:'Voorraadmanager',
            story:'Hoeveel producten staan er in de databank? Gebruik <strong>COUNT(*)</strong> om het totaal te tellen.',
            obj:'SELECT COUNT(*) FROM product',
            win:'Productaantal geteld. Voorraadrapport klaar! 📊' },
      en: { title:'How many products?', who:'Stock Manager',
            story:'How many products are in the database? Use <strong>COUNT(*)</strong> to count the total.',
            obj:'SELECT COUNT(*) FROM product',
            win:'Product count done. Stock report ready! 📊' },
    },
    disable_coupon: {
      nl: { title:'🚨 CRISIS: Kortingscode deactiveren', who:'Ines — PR',
            story:'<strong>ALARM!</strong> Kortingscode <strong>FOUT999</strong> geeft 99% korting. Al 23 klanten misbruiken hem. <strong>DEACTIVEER NU!</strong>',
            obj:'UPDATE kortingscode SET actief = 0 WHERE code = \'FOUT999\'',
            win:'Crisis bezworen! FOUT999 gedeactiveerd. 🎉' },
      en: { title:'🚨 CRISIS: Deactivate discount code', who:'Ines — PR',
            story:'<strong>ALARM!</strong> Discount code <strong>FOUT999</strong> gives 99% off. Already 23 customers are abusing it. <strong>DEACTIVATE NOW!</strong>',
            obj:'UPDATE kortingscode SET actief = 0 WHERE code = \'FOUT999\'',
            win:'Crisis averted! FOUT999 deactivated. 🎉' },
    },
    restock_webcam: {
      nl: { title:'Webcam HD bijvullen', who:'Logistiek',
            story:'Webcam HD (product_id=5): stock=0. 20 nieuwe exemplaren zijn binnen. Verwerk dit.',
            obj:'UPDATE product SET stock = 20 WHERE product_id = 5',
            win:'Webcam HD terug in stock! 📷' },
      en: { title:'Restock HD Webcam', who:'Logistics',
            story:'HD Webcam (product_id=5): stock=0. 20 new units have arrived. Process this.',
            obj:'UPDATE product SET stock = 20 WHERE product_id = 5',
            win:'HD Webcam back in stock! 📷' },
    },
    new_order: {
      nl: { title:'Bestelling verwerken', who:'Orderverwerking',
            story:'Jana Pieters (klant_id=1) bestelde 3× Notitieboek A5 (product_id=3) op 2024-12-01. Status: "verwerking".',
            obj:'INSERT INTO bestelling (klant_id, product_id, datum, aantal, status) VALUES (1, 3, \'2024-12-01\', 3, \'verwerking\')',
            win:'Bestelling verwerkt! Jana krijgt een bevestiging. 📧' },
      en: { title:'Process order', who:'Order Processing',
            story:'Jana Pieters (klant_id=1) ordered 3× Notebook A5 (product_id=3) on 2024-12-01. Status: "verwerking".',
            obj:'INSERT INTO bestelling (klant_id, product_id, datum, aantal, status) VALUES (1, 3, \'2024-12-01\', 3, \'verwerking\')',
            win:'Order processed! Jana will receive a confirmation. 📧' },
    },
    count_orders: {
      nl: { title:'Bestellingen per klant tellen', who:'Analytics',
            story:'Investeerders willen weten welke klanten het meest actief zijn. Gebruik GROUP BY.',
            obj:'SELECT klant_id, COUNT(*) FROM bestelling GROUP BY klant_id',
            win:'Rapport klaar! Investeerders tevreden. 📈' },
      en: { title:'Count orders per customer', who:'Analytics',
            story:'Investors want to know which customers are most active. Use GROUP BY.',
            obj:'SELECT klant_id, COUNT(*) FROM bestelling GROUP BY klant_id',
            win:'Report ready! Investors satisfied. 📈' },
    },
    delete_test: {
      nl: { title:'Test-bestellingen opruimen', who:'Auditor',
            story:'Testbestellingen van vóór 2024-11-12 moeten weg. Altijd WHERE bij DELETE!',
            obj:'DELETE FROM bestelling WHERE datum < \'2024-11-12\'',
            win:'Testdata verwijderd. Database proper voor het fiscale jaar. 🧹' },
      en: { title:'Clean up test orders', who:'Auditor',
            story:'Test orders before 2024-11-12 must be removed. Always use WHERE with DELETE!',
            obj:'DELETE FROM bestelling WHERE datum < \'2024-11-12\'',
            win:'Test data deleted. Database clean for the fiscal year. 🧹' },
    },
    add_telefoon: {
      nl: { title:'Telefoon: kolom aanmaken & controleren', who:'Klantenservice Chef',
            story:'Stap 1: Voeg kolom <strong>telefoon VARCHAR(20)</strong> toe aan <strong>klant</strong>. Stap 2: Zoek daarna alle klanten waarbij <strong>telefoon IS NULL</strong> — dat zijn de klanten die nog gebeld moeten worden.',
            obj:'Stap 1: ALTER TABLE klant ADD COLUMN telefoon · Stap 2: SELECT ... WHERE telefoon IS NULL',
            win:'Kolom aangemaakt én NULL-controle geslaagd! Het outreach-team weet nu wie gebeld moet worden. ☎️' },
      en: { title:'Phone: add column & check', who:'Customer Service Lead',
            story:'Step 1: Add column <strong>telefoon VARCHAR(20)</strong> to <strong>klant</strong>. Step 2: Then find all customers where <strong>telefoon IS NULL</strong> — those are the customers still to be called.',
            obj:'Step 1: ALTER TABLE klant ADD COLUMN telefoon · Step 2: SELECT ... WHERE telefoon IS NULL',
            win:'Column added and NULL check passed! The outreach team now knows who to call. ☎️' },
    },
    low_stock: {
      nl: { title:'Producten met lage stock', who:'Logistiek',
            story:'Welke producten hebben een <strong>stock van minder dan 5</strong>? Maak een urgentielijst — inclusief stock=0!',
            obj:'SELECT naam, stock FROM product WHERE stock < 5 ORDER BY stock ASC',
            win:'Urgentielijst klaar! Bestelling geplaatst bij leverancier. 📦' },
      en: { title:'Low stock products', who:'Logistics',
            story:'Which products have a <strong>stock below 5</strong>? Make an urgency list — including stock=0!',
            obj:'SELECT naam, stock FROM product WHERE stock < 5 ORDER BY stock ASC',
            win:'Urgency list ready! Order placed with supplier. 📦' },
    },
    update_order_status: {
      nl: { title:'Bestellingsstatus bijwerken', who:'Leveringsdienst',
            story:'Bestelling 4 (status "onderweg") is aangekomen! Zet status op <strong>"geleverd"</strong>.',
            obj:'UPDATE bestelling SET status = \'geleverd\' WHERE bestelling_id = 4',
            win:'Bestelling gemarkeerd als geleverd! Klant krijgt bevestiging. ✅' },
      en: { title:'Update order status', who:'Delivery Service',
            story:'Order 4 (status "onderweg") has arrived! Set status to <strong>"geleverd"</strong>.',
            obj:'UPDATE bestelling SET status = \'geleverd\' WHERE bestelling_id = 4',
            win:'Order marked as delivered! Customer receives confirmation. ✅' },
    },
    create_leverancier: {
      nl: { title:'Leverancier: tabel aanmaken & eerste rij invoegen', who:'Inkoopmanager',
            story:'DataShop werkt samen met externe leveranciers. Stap 1: Maak tabel <strong>leverancier</strong> aan (leverancier_id PK AUTO, naam NOT NULL, email, land). Stap 2: Voeg eerste leverancier toe: <strong>TechParts BV</strong>, info@techparts.be, Belgie.',
            obj:'Stap 1: CREATE TABLE leverancier · Stap 2: INSERT INTO leverancier',
            win:'Tabel aangemaakt en eerste leverancier geregistreerd! DataShop is klaar voor partnerships. 🤝' },
      en: { title:'Supplier: create table & insert first row', who:'Purchasing Manager',
            story:'DataShop works with external suppliers. Step 1: Create table <strong>leverancier</strong> (leverancier_id PK AUTO, naam NOT NULL, email, land). Step 2: Add the first supplier: <strong>TechParts BV</strong>, info@techparts.be, Belgium.',
            obj:'Step 1: CREATE TABLE leverancier · Step 2: INSERT INTO leverancier',
            win:'Table created and first supplier registered! DataShop is ready for partnerships. 🤝' },
    },
    avg_review: {
      nl: { title:'Gemiddelde reviewscore', who:'Productmanager',
            story:'Bereken de <strong>gemiddelde score</strong> van alle reviews. Gebruik AVG().',
            obj:'SELECT AVG(score) FROM review',
            win:'Gemiddelde score berekend. ⭐' },
      en: { title:'Average review score', who:'Product Manager',
            story:'Calculate the <strong>average score</strong> of all reviews. Use AVG().',
            obj:'SELECT AVG(score) FROM review',
            win:'Average score calculated. ⭐' },
    },
    expensive: {
      nl: { title:'Premium producten raadplegen', who:'CFO',
            story:'Lijst van producten duurder dan <strong>€50</strong>, duurste eerst, voor marge-analyse.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > 50 ORDER BY prijs DESC',
            win:'CFO heeft zijn rapport. Marges goed! 💰' },
      en: { title:'View premium products', who:'CFO',
            story:'List of products more expensive than <strong>€50</strong>, most expensive first, for margin analysis.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > 50 ORDER BY prijs DESC',
            win:'CFO has their report. Margins look good! 💰' },
    },
    join_orders: {
      nl: { title:'JOIN — Bestellingen met klantnamen', who:'Analytics',
            story:'Logistiek wil klantnamen, datum en status. Twee tabellen: klant en bestelling. Gebruik impliciete JOIN.',
            obj:'SELECT k.naam, b.datum, b.status FROM bestelling b, klant k WHERE b.klant_id = k.klant_id',
            win:'JOIN geslaagd! Logistiek heeft overzicht. 🔗' },
      en: { title:'JOIN — Orders with customer names', who:'Analytics',
            story:'Logistics needs customer names, date and status. Two tables: klant and bestelling. Use an implicit JOIN.',
            obj:'SELECT k.naam, b.datum, b.status FROM bestelling b, klant k WHERE b.klant_id = k.klant_id',
            win:'JOIN succeeded! Logistics has a clear overview. 🔗' },
    },
    having: {
      nl: { title:'VIP-klanten (HAVING)', who:'Analytics',
            story:'VIP-programma voor klanten met <strong>méér dan 1 bestelling</strong>. Gebruik HAVING.',
            obj:'SELECT klant_id, COUNT(*) FROM bestelling GROUP BY klant_id HAVING COUNT(*) > 1',
            win:'VIP-lijst klaar! Jana Pieters is onze trouwste klant. 👑' },
      en: { title:'VIP customers (HAVING)', who:'Analytics',
            story:'VIP programme for customers with <strong>more than 1 order</strong>. Use HAVING.',
            obj:'SELECT klant_id, COUNT(*) FROM bestelling GROUP BY klant_id HAVING COUNT(*) > 1',
            win:'VIP list ready! Jana Pieters is our most loyal customer. 👑' },
    },
    max_stock: {
      nl: { title:'Product met meeste voorraad', who:'Logistiek',
            story:'Welk product heeft de <strong>hoogste stock</strong>? Gebruik ORDER BY + LIMIT 1.',
            obj:'SELECT naam, stock FROM product ORDER BY stock DESC LIMIT 1',
            win:'Notitieboek A5 heeft hoogste stock. Opslag geoptimaliseerd! 📦' },
      en: { title:'Product with most stock', who:'Logistics',
            story:'Which product has the <strong>highest stock</strong>? Use ORDER BY + LIMIT 1.',
            obj:'SELECT naam, stock FROM product ORDER BY stock DESC LIMIT 1',
            win:'Notebook A5 has the highest stock. Storage optimised! 📦' },
    },
    products_per_category: {
      nl: { title:'Producten per categorie', who:'CFO',
            story:'Hoeveel producten zitten er per categorie in de databank? Gebruik GROUP BY.',
            obj:'SELECT categorie, COUNT(*) FROM product GROUP BY categorie',
            win:'Categorieoverzicht klaar. Elektronica domineert! 🏆' },
      en: { title:'Products per category', who:'CFO',
            story:'How many products are in each category? Use GROUP BY.',
            obj:'SELECT categorie, COUNT(*) FROM product GROUP BY categorie',
            win:'Category overview ready. Electronics dominates! 🏆' },
    },
    min_max_prijs: {
      nl: { title:'Goedkoopste & duurste product', who:'CFO',
            story:'De CFO wil de <strong>goedkoopste</strong> én <strong>duurste</strong> prijs weten in één query. Gebruik MIN() en MAX().',
            obj:'SELECT MIN(prijs), MAX(prijs) FROM product',
            win:'Prijsbereik bepaald. Perfecte input voor de winststrategie! 💶' },
      en: { title:'Cheapest & most expensive product', who:'CFO',
            story:'The CFO wants the <strong>cheapest</strong> and <strong>most expensive</strong> price in one query. Use MIN() and MAX().',
            obj:'SELECT MIN(prijs), MAX(prijs) FROM product',
            win:'Price range determined. Perfect input for the profit strategy! 💶' },
    },
    join_all: {
      nl: { title:'Megaoverzicht: klant + bestelling + product', who:'Raad van Bestuur',
            story:'De Raad van Bestuur wil <strong>één overzicht</strong>: klantnaam, productnaam en datum. Koppel drie tabellen.',
            obj:'SELECT k.naam, p.naam, b.datum FROM bestelling b, klant k, product p WHERE b.klant_id = k.klant_id AND b.product_id = p.product_id',
            win:'Megaoverzicht geleverd! De raad is onder de indruk. 🌐' },
      en: { title:'Mega overview: customer + order + product', who:'Board of Directors',
            story:'The Board wants <strong>one overview</strong>: customer name, product name and date. Join three tables.',
            obj:'SELECT k.naam, p.naam, b.datum FROM bestelling b, klant k, product p WHERE b.klant_id = k.klant_id AND b.product_id = p.product_id',
            win:'Mega overview delivered! The board is impressed. 🌐' },
    },
    distinct_steden: {
      nl: { title:'Unieke steden (DISTINCT)', who:'Marketing',
            story:'Marketing wil weten in welke <strong>unieke steden</strong> onze klanten wonen — zonder duplicaten. Gebruik <strong>DISTINCT</strong>.',
            obj:'SELECT DISTINCT stad FROM klant',
            win:'Unieke steden gevonden! Campagne per regio kan starten. 🗺️' },
      en: { title:'Unique cities (DISTINCT)', who:'Marketing',
            story:'Marketing wants to know which <strong>unique cities</strong> our customers live in — without duplicates. Use <strong>DISTINCT</strong>.',
            obj:'SELECT DISTINCT stad FROM klant',
            win:'Unique cities found! Regional campaign can start. 🗺️' },
    },
    alias_products: {
      nl: { title:'Kolomaliassen gebruiken (AS)', who:'CFO',
            story:'Het rapport moet leesbare kolomnamen bevatten. Noem <strong>naam</strong> om als <strong>product</strong> en <strong>prijs</strong> als <strong>verkoopprijs</strong>. Gebruik het sleutelwoord <strong>AS</strong>.',
            obj:'SELECT naam AS product, prijs AS verkoopprijs FROM product',
            win:'Rapport met leesbare kolomnamen klaar! CFO tevreden. 📋' },
      en: { title:'Using column aliases (AS)', who:'CFO',
            story:'The report needs readable column names. Rename <strong>naam</strong> as <strong>product</strong> and <strong>prijs</strong> as <strong>verkoopprijs</strong>. Use the keyword <strong>AS</strong>.',
            obj:'SELECT naam AS product, prijs AS verkoopprijs FROM product',
            win:'Report with readable column names ready! CFO satisfied. 📋' },
    },
    subquery_above_avg: {
      nl: { title:'Producten boven gemiddelde prijs', who:'Finance',
            story:'Welke producten kosten <strong>meer dan de gemiddelde prijs</strong>? Los dit op met een <strong>subquery</strong> in de WHERE-clausule.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > (SELECT AVG(prijs) FROM product)',
            win:'Subquery geslaagd! Premium producten geïdentificeerd. 🏆' },
      en: { title:'Products above average price', who:'Finance',
            story:'Which products cost <strong>more than the average price</strong>? Solve this with a <strong>subquery</strong> in the WHERE clause.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > (SELECT AVG(prijs) FROM product)',
            win:'Subquery succeeded! Premium products identified. 🏆' },
    },
    subquery_in: {
      nl: { title:'Klanten die ooit besteld hebben', who:'Marketing',
            story:'Welke klanten hebben <strong>minstens één bestelling</strong> geplaatst? Gebruik een subquery met <strong>IN</strong> om klant_id\'s op te zoeken in de bestelling-tabel.',
            obj:'SELECT naam, email FROM klant WHERE klant_id IN (SELECT klant_id FROM bestelling)',
            win:'Klanten met bestellingen gevonden via subquery! Gerichte marketing mogelijk. 📧' },
      en: { title:'Customers who have ever ordered', who:'Marketing',
            story:'Which customers have placed <strong>at least one order</strong>? Use a subquery with <strong>IN</strong> to look up klant_id\'s in the bestelling table.',
            obj:'SELECT naam, email FROM klant WHERE klant_id IN (SELECT klant_id FROM bestelling)',
            win:'Customers with orders found via subquery! Targeted marketing is possible. 📧' },
    },
    distinct_count: {
      nl: { title:'Hoeveel unieke steden?', who:'Marketing',
            story:'Hoeveel <strong>verschillende steden</strong> zijn er in de klantendatabank? Gebruik <strong>COUNT(DISTINCT stad)</strong> om unieke steden te tellen.',
            obj:'SELECT COUNT(DISTINCT stad) FROM klant',
            win:'Unieke steden geteld! Marketinggebieden bepaald. 🗺️' },
      en: { title:'How many unique cities?', who:'Marketing',
            story:'How many <strong>different cities</strong> are in the customer database? Use <strong>COUNT(DISTINCT stad)</strong> to count unique cities.',
            obj:'SELECT COUNT(DISTINCT stad) FROM klant',
            win:'Unique cities counted! Marketing regions determined. 🗺️' },
    },
    join_alias_order: {
      nl: { title:'JOIN met aliassen en sortering', who:'Raad van Bestuur',
            story:'Overzicht van alle bestellingen: <strong>klantnaam als "klant"</strong>, <strong>productnaam als "artikel"</strong>, datum gesorteerd van nieuwste naar oudste. Combineer JOIN + AS + ORDER BY.',
            obj:'SELECT k.naam AS klant, p.naam AS artikel, b.datum FROM bestelling b, klant k, product p WHERE b.klant_id = k.klant_id AND b.product_id = p.product_id ORDER BY b.datum DESC',
            win:'Meesterwerk! JOIN + AS + ORDER BY in één query. Raad van Bestuur staat te klappen. 👏' },
      en: { title:'JOIN with aliases and sorting', who:'Board of Directors',
            story:'Overview of all orders: <strong>customer name as "klant"</strong>, <strong>product name as "artikel"</strong>, date sorted newest first. Combine JOIN + AS + ORDER BY.',
            obj:'SELECT k.naam AS klant, p.naam AS artikel, b.datum FROM bestelling b, klant k, product p WHERE b.klant_id = k.klant_id AND b.product_id = p.product_id ORDER BY b.datum DESC',
            win:'Masterpiece! JOIN + AS + ORDER BY in one query. Board of Directors applauds. 👏' },
    },
    inner_join_basic: {
      nl: { title:'INNER JOIN: klanten en bestellingen', who:'Analytics',
            story:'Tijd voor de ANSI-standaard! Haal alle klanten op <strong>samen met hun besteldatum</strong> via een <strong>INNER JOIN</strong>. Alleen klanten die besteld hebben verschijnen in het resultaat.',
            obj:'SELECT klant.naam, bestelling.datum FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id',
            win:'Perfecte INNER JOIN! Enkel klanten met bestellingen zichtbaar. ANSI-syntax onder de knie. ✅' },
      en: { title:'INNER JOIN: customers and orders', who:'Analytics',
            story:'Time for the ANSI standard! Get all customers <strong>together with their order date</strong> via an <strong>INNER JOIN</strong>. Only customers who have ordered appear in the result.',
            obj:'SELECT klant.naam, bestelling.datum FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id',
            win:'Perfect INNER JOIN! Only customers with orders visible. ANSI syntax mastered. ✅' },
    },
    left_join_all: {
      nl: { title:'LEFT JOIN: ook klanten zonder bestelling', who:'Analytics',
            story:'We willen <strong>ALLE klanten</strong> zien, ook wie nog nooit iets besteld heeft. Gebruik een <strong>LEFT JOIN</strong> zodat klanten zonder bestelling ook verschijnen (met NULL als datum).',
            obj:'SELECT klant.naam, bestelling.datum FROM klant LEFT JOIN bestelling ON klant.klant_id = bestelling.klant_id',
            win:'LEFT JOIN geslaagd! Lena is onder de indruk: ook klanten zonder bestelling zijn zichtbaar. 🎯' },
      en: { title:'LEFT JOIN: including customers without orders', who:'Analytics',
            story:'We want to see <strong>ALL customers</strong>, including those who have never ordered. Use a <strong>LEFT JOIN</strong> so customers without orders also appear (with NULL as date).',
            obj:'SELECT klant.naam, bestelling.datum FROM klant LEFT JOIN bestelling ON klant.klant_id = bestelling.klant_id',
            win:'LEFT JOIN succeeded! Even customers without orders are visible. 🎯' },
    },
    join_three_tables: {
      nl: { title:'3-weg JOIN: klant + bestelling + product', who:'Raad van Bestuur',
            story:'De board wil weten <strong>wie wat besteld heeft</strong>: klantnaam, productnaam en aankoopprijs. Koppel <strong>drie tabellen</strong> via twee INNER JOINs.',
            obj:'SELECT klant.naam, product.naam, product.prijs FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id INNER JOIN product ON bestelling.product_id = product.product_id',
            win:'3-tabel JOIN in één query! Dit is enterprise-niveau SQL. Board of Directors applauds. 👏' },
      en: { title:'3-way JOIN: customer + order + product', who:'Board of Directors',
            story:'The board wants to know <strong>who ordered what</strong>: customer name, product name and purchase price. Join <strong>three tables</strong> using two INNER JOINs.',
            obj:'SELECT klant.naam, product.naam, product.prijs FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id INNER JOIN product ON bestelling.product_id = product.product_id',
            win:'3-table JOIN in one query! This is enterprise-level SQL. Board of Directors applauds. 👏' },
    },
    join_with_where: {
      nl: { title:'JOIN + WHERE: Gentse bestellingen', who:'Marketing',
            story:'Marketing wil een lijst van klanten uit <strong>Gent</strong> met hun bestellingen. Combineer een <strong>INNER JOIN</strong> met een <strong>WHERE</strong>-filter op stad.',
            obj:'SELECT klant.naam, bestelling.datum, bestelling.status FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id WHERE klant.stad = \'Gent\'',
            win:'JOIN + WHERE gecombineerd! Gentse klanten met hun orders in beeld voor gerichte campagnes. 📍' },
      en: { title:'JOIN + WHERE: Ghent orders', who:'Marketing',
            story:'Marketing wants a list of customers from <strong>Ghent</strong> with their orders. Combine an <strong>INNER JOIN</strong> with a <strong>WHERE</strong> filter on city.',
            obj:'SELECT klant.naam, bestelling.datum, bestelling.status FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id WHERE klant.stad = \'Gent\'',
            win:'JOIN + WHERE combined! Ghent customers with their orders visible for targeted campaigns. 📍' },
    },
    groupby_category: {
      nl: { title:'Omzet per categorie', who:'CFO',
            story:'Kwartaalrapport! Bereken de <strong>totale omzet per productcategorie</strong> via <strong>SUM(prijs)</strong> gegroepeerd op categorie. Sorteer van hoog naar laag.',
            obj:'SELECT categorie, SUM(prijs) FROM product GROUP BY categorie ORDER BY SUM(prijs) DESC',
            win:'Omzet per categorie berekend! Elektronica loopt duidelijk het best. Financieel rapport klaar. 📈' },
      en: { title:'Revenue per category', who:'CFO',
            story:'Quarterly report! Calculate the <strong>total revenue per product category</strong> using <strong>SUM(prijs)</strong> grouped by category. Sort from high to low.',
            obj:'SELECT categorie, SUM(prijs) FROM product GROUP BY categorie ORDER BY SUM(prijs) DESC',
            win:'Revenue per category calculated! Electronics clearly leads. Financial report ready. 📈' },
    },
    groupby_having: {
      nl: { title:'HAVING: categorieën met hoge gemiddelde prijs', who:'Finance',
            story:'We willen enkel categorieën zien met een <strong>gemiddelde prijs boven €30</strong>. Gebruik <strong>GROUP BY + HAVING</strong> om groepen te filteren na aggregatie.',
            obj:'SELECT categorie, AVG(prijs) FROM product GROUP BY categorie HAVING AVG(prijs) > 30',
            win:'HAVING gemeisterd! Enkel dure categorieën zichtbaar. Dit is het verschil tussen WHERE en HAVING. 🏆' },
      en: { title:'HAVING: categories with high average price', who:'Finance',
            story:'We only want to see categories with an <strong>average price above €30</strong>. Use <strong>GROUP BY + HAVING</strong> to filter groups after aggregation.',
            obj:'SELECT categorie, AVG(prijs) FROM product GROUP BY categorie HAVING AVG(prijs) > 30',
            win:'HAVING mastered! Only expensive categories visible. That\'s the difference between WHERE and HAVING. 🏆' },
    },
    groupby_count_status: {
      nl: { title:'Bestellingen per status tellen', who:'Logistiek',
            story:'Logistiek wil weten hoeveel bestellingen er per status zijn (geleverd, onderweg, verwerking). Gebruik <strong>COUNT(*) + GROUP BY status</strong>.',
            obj:'SELECT status, COUNT(*) FROM bestelling GROUP BY status',
            win:'Logistiek rapport klaar! Per status weten we exact hoeveel bestellingen wachten. 🚚' },
      en: { title:'Count orders per status', who:'Logistics',
            story:'Logistics wants to know how many orders there are per status (delivered, in transit, processing). Use <strong>COUNT(*) + GROUP BY status</strong>.',
            obj:'SELECT status, COUNT(*) FROM bestelling GROUP BY status',
            win:'Logistics report ready! We now know exactly how many orders are waiting per status. 🚚' },
    },
    create_table_leverancier: {
      nl: { title:'CREATE TABLE + INSERT: leveranciers beheren', who:'Inkoopmanager',
            story:'Herhaling op expert-niveau. Stap 1: Maak tabel <strong>leverancier</strong> opnieuw aan (leverancier_id PK AUTO_INCREMENT, naam NOT NULL, email, land). Stap 2: Voeg meteen een tweede leverancier in: <strong>CloudBase NV</strong>, cloud@cloudbase.be, Nederland.',
            obj:'Stap 1: CREATE TABLE leverancier · Stap 2: INSERT tweede leverancier',
            win:'Tabel aangemaakt en leverancier ingevoegd! Expert-niveau DDL + DML gecombineerd. 🏗️' },
      en: { title:'CREATE TABLE + INSERT: manage suppliers', who:'Purchasing Manager',
            story:'Expert-level recap. Step 1: Create table <strong>leverancier</strong> again (leverancier_id PK AUTO_INCREMENT, naam NOT NULL, email, land). Step 2: Immediately insert a second supplier: <strong>CloudBase NV</strong>, cloud@cloudbase.be, Netherlands.',
            obj:'Step 1: CREATE TABLE leverancier · Step 2: INSERT second supplier',
            win:'Table created and supplier inserted! Expert-level DDL + DML combined. 🏗️' },
    },
    alter_add_column: {
      nl: { title:'ALTER TABLE: kolom toevoegen & vullen', who:'Lena — Lead Engineer',
            story:'Stap 1: Voeg kolom <strong>geboortedatum DATE</strong> toe aan tabel <strong>klant</strong>. Stap 2: Vul het geboortedatum van Jana Pieters (klant_id=1) in: <strong>1990-03-15</strong>. Zo zie je het verschil tussen structuur aanpassen (DDL) en data aanpassen (DML).',
            obj:'Stap 1: ALTER TABLE klant ADD COLUMN geboortedatum · Stap 2: UPDATE klant SET geboortedatum',
            win:'DDL geslaagd — de structuur is aangepast. Data ingevoerd via DML. Perfect gecombineerd! 🏗️' },
      en: { title:'ALTER TABLE: add column & fill it', who:'Lena — Lead Engineer',
            story:'Step 1: Add column <strong>geboortedatum DATE</strong> to table <strong>klant</strong>. Step 2: Fill in the birthdate of Jana Pieters (klant_id=1): <strong>1990-03-15</strong>. This shows the difference between changing structure (DDL) and changing data (DML).',
            obj:'Step 1: ALTER TABLE klant ADD COLUMN geboortedatum · Step 2: UPDATE klant SET geboortedatum',
            win:'DDL succeeded — structure updated. Data entered via DML. Perfectly combined! 🏗️' },
    },
    join_having_advanced: {
      nl: { title:'JOIN + GROUP BY + HAVING: topklanten', who:'Venture Capitalist',
            story:'De investeerders willen de <strong>klanten die meer dan 1 bestelling</strong> geplaatst hebben. Koppel klant aan bestelling, groepeer per klant en filter via HAVING. Dit is het meest geavanceerde patroon in SQL.',
            obj:'SELECT klant.naam, COUNT(*) FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id GROUP BY klant.naam HAVING COUNT(*) > 1',
            win:'JOIN + GROUP BY + HAVING in één query! Dit is het niveau van een senior data engineer. Investeerders tekenen. 🌟💰' },
      en: { title:'JOIN + GROUP BY + HAVING: top customers', who:'Venture Capitalist',
            story:'The investors want to see <strong>customers with more than 1 order</strong>. Join customer to order, group per customer and filter via HAVING. This is the most advanced SQL pattern.',
            obj:'SELECT klant.naam, COUNT(*) FROM klant INNER JOIN bestelling ON klant.klant_id = bestelling.klant_id GROUP BY klant.naam HAVING COUNT(*) > 1',
            win:'JOIN + GROUP BY + HAVING in one query! This is senior data engineer level. Investors are signing. 🌟💰' },
    },
    delete_review: {
      nl: { title:'Slechte review verwijderen', who:'Klantenservice',
            story:'Klant Lena Maes dient een verwijderverzoek in voor haar review (review_id=3). Verwijder alleen die review.',
            obj:'DELETE FROM review WHERE review_id = 3',
            win:'Review verwijderd. Verzoek GDPR-conform verwerkt. ✅' },
      en: { title:'Delete bad review', who:'Customer Service',
            story:'Customer Lena Maes submits a deletion request for her review (review_id=3). Delete only that review.',
            obj:'DELETE FROM review WHERE review_id = 3',
            win:'Review deleted. Request processed in GDPR compliance. ✅' },
    },
    insert_review: {
      nl: { title:'Klantreview toevoegen', who:'Klantenservice',
            story:'Jana Pieters (klant_id=1) geeft product 3 (Notitieboek A5) een score van <strong>5</strong> met commentaar <strong>"Top kwaliteit!"</strong>.',
            obj:'INSERT INTO review (klant_id, product_id, score, commentaar) VALUES (1, 3, 5, \'Top kwaliteit!\')',
            win:'Review opgeslagen! Jana is blij gehoord te worden. ⭐' },
      en: { title:'Add customer review', who:'Customer Service',
            story:'Jana Pieters (klant_id=1) gives product 3 (Notebook A5) a score of <strong>5</strong> with comment <strong>"Top kwaliteit!"</strong>.',
            obj:'INSERT INTO review (klant_id, product_id, score, commentaar) VALUES (1, 3, 5, \'Top kwaliteit!\')',
            win:'Review saved! Jana is happy to be heard. ⭐' },
    },
    activate_coupon: {
      nl: { title:'Kortingscode activeren', who:'Marketing',
            story:'Zomercampagne! Kortingscode <strong>ZOMER20</strong> moet geactiveerd worden (actief = 1).',
            obj:'UPDATE kortingscode SET actief = 1 WHERE code = \'ZOMER20\'',
            win:'ZOMER20 geactiveerd! Campagne kan starten. 🌞' },
      en: { title:'Activate discount code', who:'Marketing',
            story:'Summer campaign! Discount code <strong>ZOMER20</strong> must be activated (actief = 1).',
            obj:'UPDATE kortingscode SET actief = 1 WHERE code = \'ZOMER20\'',
            win:'ZOMER20 activated! Campaign can start. 🌞' },
    },
    delete_inactive: {
      nl: { title:'Inactieve klant verwijderen', who:'Auditor',
            story:'Audit resultaat: klant_id=4 (Kobe Janssen) is inactief en heeft nooit besteld. Hij mag volledig verwijderd worden.',
            obj:'DELETE FROM klant WHERE klant_id = 4',
            win:'Kobe correct verwijderd uit de databank. 🧹' },
      en: { title:'Delete inactive customer', who:'Auditor',
            story:'Audit result: klant_id=4 (Kobe Janssen) is inactive and has never ordered. He can be fully removed.',
            obj:'DELETE FROM klant WHERE klant_id = 4',
            win:'Kobe correctly deleted from the database. 🧹' },
    },
    insert_coupon: {
      nl: { title:'Nieuwe kortingscode aanmaken', who:'Marketing',
            story:'Zwarte Vrijdag! Maak kortingscode <strong>BLACK30</strong> aan: <strong>30%</strong> korting, actief (1), gebruik <strong>0</strong>.',
            obj:'INSERT INTO kortingscode (code, korting, actief, gebruik) VALUES (\'BLACK30\', 30, 1, 0)',
            win:'BLACK30 aangemaakt! Klanten gaan genieten van 30% korting. 🛍️' },
      en: { title:'Create new discount code', who:'Marketing',
            story:'Black Friday! Create discount code <strong>BLACK30</strong>: <strong>30%</strong> off, active (1), usage <strong>0</strong>.',
            obj:'INSERT INTO kortingscode (code, korting, actief, gebruik) VALUES (\'BLACK30\', 30, 1, 0)',
            win:'BLACK30 created! Customers will enjoy 30% off. 🛍️' },
    },
    update_stock_category: {
      nl: { title:'Elektronicastock verhogen', who:'Logistiek',
            story:'Grote levering elektronica binnen! Verhoog de stock van <strong>alle Elektronica-producten</strong> met <strong>10</strong>.',
            obj:'UPDATE product SET stock = stock + 10 WHERE categorie = \'Elektronica\'',
            win:'Elektronicastock opgehoogd! Geen tekorten meer. ⚡' },
      en: { title:'Increase electronics stock', who:'Logistics',
            story:'Large electronics delivery arrived! Increase the stock of <strong>all Electronics products</strong> by <strong>10</strong>.',
            obj:'UPDATE product SET stock = stock + 10 WHERE categorie = \'Elektronica\'',
            win:'Electronics stock increased! No more shortages. ⚡' },
    },
    delete_product_reviews: {
      nl: { title:'Reviews van gestopt product wissen', who:'Productmanager',
            story:'Product 3 (Notitieboek A5) wordt stopgezet. Verwijder alle reviews van product_id=3 vóór het product zelf weg kan.',
            obj:'DELETE FROM review WHERE product_id = 3',
            win:'Reviews verwijderd. Product kan nu volledig uit de databank. 🧹' },
      en: { title:'Delete reviews of discontinued product', who:'Product Manager',
            story:'Product 3 (Notebook A5) is being discontinued. Delete all reviews of product_id=3 before the product itself can be removed.',
            obj:'DELETE FROM review WHERE product_id = 3',
            win:'Reviews deleted. Product can now be fully removed from the database. 🧹' },
    },
    delete_no_orders: {
      nl: { title:'Klanten zonder bestelling verwijderen', who:'Data Engineer',
            story:'Dataopschoning: verwijder alle klanten die <strong>nooit een bestelling</strong> hebben geplaatst. Gebruik NOT IN met een subquery.',
            obj:'DELETE FROM klant WHERE klant_id NOT IN (SELECT klant_id FROM bestelling)',
            win:'Klanten zonder bestellingen opgeruimd. Zuivere databank! 🧹' },
      en: { title:'Delete customers without orders', who:'Data Engineer',
            story:'Data cleanup: delete all customers who have <strong>never placed an order</strong>. Use NOT IN with a subquery.',
            obj:'DELETE FROM klant WHERE klant_id NOT IN (SELECT klant_id FROM bestelling)',
            win:'Customers without orders cleaned up. Pure database! 🧹' },
    },
    insert_bulk_order: {
      nl: { title:'Bestelling van topklant verwerken', who:'Orderverwerking',
            story:'Fatima El Asri (klant_id=5) bestelde 2x Ergonomische stoel (product_id=4) op <strong>2025-01-15</strong>. Status: <strong>"verwerking"</strong>.',
            obj:'INSERT INTO bestelling (klant_id, product_id, datum, aantal, status) VALUES (5, 4, \'2025-01-15\', 2, \'verwerking\')',
            win:'Bestellingsverwerking afgerond. Fatima krijgt een bevestiging. 📧' },
      en: { title:'Process top customer order', who:'Order Processing',
            story:'Fatima El Asri (klant_id=5) ordered 2x Ergonomic Chair (product_id=4) on <strong>2025-01-15</strong>. Status: <strong>"verwerking"</strong>.',
            obj:'INSERT INTO bestelling (klant_id, product_id, datum, aantal, status) VALUES (5, 4, \'2025-01-15\', 2, \'verwerking\')',
            win:'Order processing complete. Fatima will receive a confirmation. 📧' },
    },
    update_top_discount: {
      nl: { title:'VIP kortingscode upgraden', who:'Marketing',
            story:'VIP-actie: verhoog de korting van <strong>TROUW15</strong> naar <strong>25%</strong> én verhoog het gebruik met 1 (loyaliteitsbonus).',
            obj:'UPDATE kortingscode SET korting = 25, gebruik = gebruik + 1 WHERE code = \'TROUW15\'',
            win:'TROUW15 bijgewerkt naar 25% korting. VIP-klant in de wolken! 👑' },
      en: { title:'Upgrade VIP discount code', who:'Marketing',
            story:'VIP action: increase the discount of <strong>TROUW15</strong> to <strong>25%</strong> and increase usage by 1 (loyalty bonus).',
            obj:'UPDATE kortingscode SET korting = 25, gebruik = gebruik + 1 WHERE code = \'TROUW15\'',
            win:'TROUW15 updated to 25% discount. VIP customer is thrilled! 👑' },
    },
    delete_old_reviews: {
      nl: { title:'Negatieve reviews opschonen', who:'Productmanager',
            story:'Negatieve reviews (score ≤ 2) schaden de reputatie. Verwijder alle reviews met score <strong>kleiner dan of gelijk aan 2</strong>.',
            obj:'DELETE FROM review WHERE score <= 2',
            win:'Lage reviews verwijderd. Reputatie hersteld! ⭐' },
      en: { title:'Clean up negative reviews', who:'Product Manager',
            story:'Negative reviews (score ≤ 2) damage the reputation. Delete all reviews with a score <strong>less than or equal to 2</strong>.',
            obj:'DELETE FROM review WHERE score <= 2',
            win:'Low reviews deleted. Reputation restored! ⭐' },
    },
    like_search: {
      nl: { title:'Klanten zoeken op naam', who:'Marketing',
            story:'Marketing wil een campagne sturen naar alle klanten waarvan de naam begint met de letter <strong>J</strong>. Gebruik <strong>LIKE</strong> om op naampatroon te filteren.',
            obj:'SELECT naam, email FROM klant WHERE naam LIKE \'J%\'',
            win:'J-klanten gevonden! Campagne verstuurd. 📣' },
      en: { title:'Search customers by name', who:'Marketing',
            story:'Marketing wants to send a campaign to all customers whose name starts with the letter <strong>J</strong>. Use <strong>LIKE</strong> to filter by name pattern.',
            obj:'SELECT naam, email FROM klant WHERE naam LIKE \'J%\'',
            win:'J-customers found! Campaign sent. 📣' },
    },
    between_price: {
      nl: { title:'Middensegment producten', who:'Inkoop',
            story:'Inkoop zoekt producten in het middensegment: prijs <strong>tussen €20 en €80</strong> (inclusief). Gebruik <strong>BETWEEN</strong>.',
            obj:'SELECT naam, prijs FROM product WHERE prijs BETWEEN 20 AND 80',
            win:'Middensegment in kaart gebracht! Inkoopstrategie klaar. 💼' },
      en: { title:'Mid-range products', who:'Purchasing',
            story:'Purchasing is looking for mid-range products: price <strong>between €20 and €80</strong> (inclusive). Use <strong>BETWEEN</strong>.',
            obj:'SELECT naam, prijs FROM product WHERE prijs BETWEEN 20 AND 80',
            win:'Mid-range mapped! Purchasing strategy ready. 💼' },
    },
    null_email: {
      nl: { title:'Klanten zonder e-mailadres', who:'Data Engineer',
            story:'Dataopschoning: welke klanten hebben <strong>geen e-mailadres</strong> ingevuld? Gebruik <strong>IS NULL</strong> — nooit <code>= NULL</code>!',
            obj:'SELECT naam FROM klant WHERE email IS NULL',
            win:'Klanten zonder e-mail gevonden. Klantenservice neemt contact op via post. 📬' },
      en: { title:'Customers without email address', who:'Data Engineer',
            story:'Data cleanup: which customers have <strong>no email address</strong> filled in? Use <strong>IS NULL</strong> — never <code>= NULL</code>!',
            obj:'SELECT naam FROM klant WHERE email IS NULL',
            win:'Customers without email found. Customer service will contact them by post. 📬' },
    },
    not_in_products: {
      nl: { title:'Producten zonder reviews', who:'Productmanager',
            story:'Welke producten hebben <strong>nog nooit een review</strong> ontvangen? Gebruik <strong>NOT IN</strong> met een subquery op de review-tabel.',
            obj:'SELECT naam FROM product WHERE product_id NOT IN (SELECT product_id FROM review)',
            win:'Producten zonder feedback geïdentificeerd. Inkoopteam stuurt testpakketjes. 📦' },
      en: { title:'Products without reviews', who:'Product Manager',
            story:'Which products have <strong>never received a review</strong>? Use <strong>NOT IN</strong> with a subquery on the review table.',
            obj:'SELECT naam FROM product WHERE product_id NOT IN (SELECT product_id FROM review)',
            win:'Products without feedback identified. Purchasing team sends test packages. 📦' },
    },
    anti_join_no_orders: {
      nl: { title:'Klanten die nog nooit besteld hebben', who:'Marketing',
            story:'Marketing wil klanten activeren die <strong>nooit een bestelling</strong> hebben geplaatst. Gebruik een <strong>LEFT JOIN + WHERE IS NULL</strong> (anti-join patroon).',
            obj:'SELECT klant.naam, klant.email FROM klant LEFT JOIN bestelling ON klant.klant_id = bestelling.klant_id WHERE bestelling.klant_id IS NULL',
            win:'Anti-join geslaagd! Inactieve klanten gevonden. Reactivatiecampagne klaar. 📧' },
      en: { title:'Customers who have never ordered', who:'Marketing',
            story:'Marketing wants to activate customers who have <strong>never placed an order</strong>. Use a <strong>LEFT JOIN + WHERE IS NULL</strong> (anti-join pattern).',
            obj:'SELECT klant.naam, klant.email FROM klant LEFT JOIN bestelling ON klant.klant_id = bestelling.klant_id WHERE bestelling.klant_id IS NULL',
            win:'Anti-join succeeded! Inactive customers found. Reactivation campaign ready. 📧' },
    },
    like_product_search: {
      nl: { title:'Producten zoeken op sleutelwoord', who:'Webshop',
            story:'De zoekbalk van de webshop filtert producten op naam. Zoek alle producten waarvan de naam <strong>"Cam"</strong> bevat — klanten zoeken naar camera\'s en webcams.',
            obj:'SELECT naam, prijs, stock FROM product WHERE naam LIKE \'%Cam%\'',
            win:'Zoekresultaten gevonden! Webcam HD en Camera-producten zichtbaar. 📷' },
      en: { title:'Search products by keyword', who:'Webshop',
            story:'The webshop search bar filters products by name. Find all products whose name contains <strong>"Cam"</strong> — customers are searching for cameras and webcams.',
            obj:'SELECT naam, prijs, stock FROM product WHERE naam LIKE \'%Cam%\'',
            win:'Search results found! HD Webcam and Camera products visible. 📷' },
    },
    between_dates: {
      nl: { title:'Bestellingen van Q4 2024', who:'Finance',
            story:'Kwartaalrapport: haal alle bestellingen op van <strong>Q4 2024</strong> — van 1 oktober tot en met 31 december 2024. Gebruik <strong>BETWEEN</strong> met datums.',
            obj:'SELECT bestelling_id, datum, status FROM bestelling WHERE datum BETWEEN \'2024-10-01\' AND \'2024-12-31\'',
            win:'Q4-rapport klaar! Alle bestellingen van het laatste kwartaal in beeld. 📊' },
      en: { title:'Orders from Q4 2024', who:'Finance',
            story:'Quarterly report: get all orders from <strong>Q4 2024</strong> — from 1 October to 31 December 2024. Use <strong>BETWEEN</strong> with dates.',
            obj:'SELECT bestelling_id, datum, status FROM bestelling WHERE datum BETWEEN \'2024-10-01\' AND \'2024-12-31\'',
            win:'Q4 report ready! All orders from the last quarter visible. 📊' },
    },
    case_stock_status: {
      nl: { title:'Stockstatus labelen met CASE WHEN', who:'Logistiek',
            story:'Logistiek wil een overzicht met een leesbare <strong>stockstatus</strong>: "Uitverkocht" als stock = 0, "Bijna op" als stock < 5, anders "Op voorraad". Gebruik <strong>CASE WHEN</strong>.',
            obj:'SELECT naam, stock, CASE WHEN stock = 0 THEN \'Uitverkocht\' WHEN stock < 5 THEN \'Bijna op\' ELSE \'Op voorraad\' END AS status FROM product',
            win:'CASE WHEN gemeisterd! Stockoverzicht met leesbare labels. Logistiek blij! 🏷️' },
      en: { title:'Label stock status with CASE WHEN', who:'Logistics',
            story:'Logistics wants an overview with a readable <strong>stock status</strong>: "Uitverkocht" if stock = 0, "Bijna op" if stock < 5, otherwise "Op voorraad". Use <strong>CASE WHEN</strong>.',
            obj:'SELECT naam, stock, CASE WHEN stock = 0 THEN \'Uitverkocht\' WHEN stock < 5 THEN \'Bijna op\' ELSE \'Op voorraad\' END AS status FROM product',
            win:'CASE WHEN mastered! Stock overview with readable labels. Logistics happy! 🏷️' },
    },
    join_product_review: {
      nl: { title:'Producten met hun reviews', who:'Marketing',
            story:'Marketing wil een overzicht van <strong>producten met hun gemiddelde reviewscore</strong>. Koppel de tabel product aan review via product_id.',
            obj:'SELECT p.naam, AVG(r.score) AS gemiddelde FROM product p INNER JOIN review r ON p.product_id = r.product_id GROUP BY p.product_id, p.naam',
            win:'Reviewoverzicht klaar! Marketing heeft nu een duidelijk beeld van klanttevredenheid per product. 🌟' },
      en: { title:'Products with their reviews', who:'Marketing',
            story:'Marketing wants an overview of <strong>products with their average review score</strong>. Join the product table to review via product_id.',
            obj:'SELECT p.naam, AVG(r.score) AS gemiddelde FROM product p INNER JOIN review r ON p.product_id = r.product_id GROUP BY p.product_id, p.naam',
            win:'Review overview ready! Marketing now has a clear picture of customer satisfaction per product. 🌟' },
    },
    subquery_expensive: {
      nl: { title:'Producten duurder dan gemiddeld', who:'Finance',
            story:'Finance wil een lijst van <strong>producten die duurder zijn dan het gemiddelde</strong>. Gebruik een subquery om het gemiddelde te berekenen.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > (SELECT AVG(prijs) FROM product) ORDER BY prijs DESC',
            win:'Subquery gemeisterd! Finance heeft nu een lijst van premium producten boven het gemiddelde. 💎' },
      en: { title:'Products more expensive than average', who:'Finance',
            story:'Finance wants a list of <strong>products that are more expensive than average</strong>. Use a subquery to calculate the average.',
            obj:'SELECT naam, prijs FROM product WHERE prijs > (SELECT AVG(prijs) FROM product) ORDER BY prijs DESC',
            win:'Subquery mastered! Finance now has a list of premium products above average. 💎' },
    },
    update_email: {
      nl: { title:'E-mailadres bijwerken', who:'Klantenservice',
            story:'Klant Jana Pieters (klant_id=1) heeft haar e-mailadres gewijzigd naar <strong>jana.pieters@nieuw.be</strong>. Update de database.',
            obj:'UPDATE klant SET email = \'jana.pieters@nieuw.be\' WHERE klant_id = 1',
            win:'E-mail bijgewerkt! Jana kan nu inloggen met haar nieuwe adres. 📬' },
      en: { title:'Update email address', who:'Customer Service',
            story:'Customer Jana Pieters (klant_id=1) has changed her email to <strong>jana.pieters@nieuw.be</strong>. Update the database.',
            obj:'UPDATE klant SET email = \'jana.pieters@nieuw.be\' WHERE klant_id = 1',
            win:'Email updated! Jana can now log in with her new address. 📬' },
    },
    search_by_email_domain: {
      nl: { title:'Klanten op e-maildomein zoeken', who:'IT',
            story:'IT wil alle klanten vinden met een <strong>@mail.be</strong> e-mailadres voor een security-controle.',
            obj:'SELECT naam, email FROM klant WHERE email LIKE \'%@mail.be\'',
            win:'Security-controle klaar! Alle @mail.be klanten gevonden. 🔐' },
      en: { title:'Search customers by email domain', who:'IT',
            story:'IT wants to find all customers with a <strong>@mail.be</strong> email address for a security check.',
            obj:'SELECT naam, email FROM klant WHERE email LIKE \'%@mail.be\'',
            win:'Security check done! All @mail.be customers found. 🔐' },
    },
    revenue_per_customer: {
      nl: { title:'Omzet per klant berekenen', who:'CFO',
            story:'De CFO wil weten hoeveel <strong>elke klant totaal heeft besteld</strong> (som van totaal_prijs). Sorteer op omzet aflopend.',
            obj:'SELECT k.naam, SUM(b.totaal_prijs) AS omzet FROM klant k INNER JOIN bestelling b ON k.klant_id = b.klant_id GROUP BY k.klant_id, k.naam ORDER BY omzet DESC',
            win:'Omzetranking klaar! De CFO ziet nu wie de top-klanten zijn. 🏆' },
      en: { title:'Calculate revenue per customer', who:'CFO',
            story:'The CFO wants to know how much <strong>each customer has ordered in total</strong> (sum of totaal_prijs). Sort by revenue descending.',
            obj:'SELECT k.naam, SUM(b.totaal_prijs) AS omzet FROM klant k INNER JOIN bestelling b ON k.klant_id = b.klant_id GROUP BY k.klant_id, k.naam ORDER BY omzet DESC',
            win:'Revenue ranking ready! The CFO can now see who the top customers are. 🏆' },
    },
    select_all_products: {
      nl: { title:'Alle producten bekijken', who:'CEO — jij',
            story:'Je hebt net toegang tot de database. Bekijk alle producten om een overzicht te krijgen van het assortiment.',
            obj:'SELECT * FROM product',
            win:'Perfect! Je ziet nu alle producten. Zo krijg je snel overzicht. 🎉' },
      en: { title:'View all products', who:'CEO — you',
            story:'You just got access to the database. View all products to get an overview of the range.',
            obj:'SELECT * FROM product',
            win:'Perfect! You can now see all products. Great way to get a quick overview. 🎉' },
    },
    count_klanten: {
      nl: { title:'Hoeveel klanten zijn er?', who:'Investeerder',
            story:'Een investeerder vraagt hoeveel klanten DataShop heeft. Tel alle rijen in de klant-tabel.',
            obj:'SELECT COUNT(*) AS aantal_klanten FROM klant',
            win:'Geteld! Je weet nu exact hoeveel klanten er zijn. 📊' },
      en: { title:'How many customers are there?', who:'Investor',
            story:'An investor asks how many customers DataShop has. Count all rows in the klant table.',
            obj:'SELECT COUNT(*) AS aantal_klanten FROM klant',
            win:'Counted! You now know exactly how many customers there are. 📊' },
    },
    join_top_products: {
      nl: { title:'Bestsellers via bestellingen', who:'Investeerder',
            story:'De investeerder wil weten welke producten het vaakst besteld zijn. JOIN product en bestelling, tel bestellingen per product, sorteer aflopend.',
            obj:'SELECT p.naam, COUNT(b.bestelling_id) AS aantal FROM product p LEFT JOIN bestelling b ON p.product_id = b.product_id GROUP BY p.product_id, p.naam ORDER BY aantal DESC',
            win:'Bestseller-ranking klaar! De investor is onder de indruk. 🏆' },
      en: { title:'Bestsellers via orders', who:'Investor',
            story:'The investor wants to know which products are ordered most often. JOIN product and bestelling, count orders per product, sort descending.',
            obj:'SELECT p.naam, COUNT(b.bestelling_id) AS aantal FROM product p LEFT JOIN bestelling b ON p.product_id = b.product_id GROUP BY p.product_id, p.naam ORDER BY aantal DESC',
            win:'Bestseller ranking ready! The investor is impressed. 🏆' },
    },
    update_stock_bulk: {
      nl: { title:'Stock aanvullen na levering', who:'Logistiek',
            story:'Er is een levering binnengekomen. Verhoog de stock van ALLE producten met categorie "Elektronica" met 10.',
            obj:'UPDATE product SET stock = stock + 10 WHERE categorie = \'Elektronica\'',
            win:'Voorraad bijgewerkt! Alle elektronica-producten hebben 10 extra stuks. 📦' },
      en: { title:'Top up stock after delivery', who:'Logistics',
            story:'A delivery has arrived. Increase the stock of ALL products with category "Elektronica" by 10.',
            obj:'UPDATE product SET stock = stock + 10 WHERE categorie = \'Elektronica\'',
            win:'Stock updated! All electronics products have 10 extra units. 📦' },
    },
    select_active_products: {
      nl: { title:'Producten in stock', who:'Webshop',
            story:'De webshop toont alleen producten met meer dan 0 stuks op voorraad. Haal alle producten op waar <strong>stock > 0</strong>.',
            obj:'SELECT naam, prijs, stock FROM product WHERE stock > 0 ORDER BY stock DESC',
            win:'Productoverzicht klaar! De webshop toont nu alleen leverbare producten. ✅' },
      en: { title:'Products in stock', who:'Webshop',
            story:'The webshop only shows products with more than 0 units in stock. Get all products where <strong>stock > 0</strong>.',
            obj:'SELECT naam, prijs, stock FROM product WHERE stock > 0 ORDER BY stock DESC',
            win:'Product overview ready! The webshop now only shows deliverable products. ✅' },
    },
    subquery_top_customer: {
      nl: { title:'Klant met meeste bestellingen', who:'Marketing',
            story:'Zoek de naam van de klant die de <strong>meeste bestellingen</strong> heeft geplaatst. Gebruik een subquery of GROUP BY + LIMIT.',
            obj:'SELECT k.naam, COUNT(b.bestelling_id) AS totaal FROM klant k JOIN bestelling b ON k.klant_id = b.klant_id GROUP BY k.klant_id, k.naam ORDER BY totaal DESC LIMIT 1',
            win:'VIP-klant gevonden! Dit is goud voor de marketingafdeling. 👑' },
      en: { title:'Customer with most orders', who:'Marketing',
            story:'Find the name of the customer who has placed the <strong>most orders</strong>. Use a subquery or GROUP BY + LIMIT.',
            obj:'SELECT k.naam, COUNT(b.bestelling_id) AS totaal FROM klant k JOIN bestelling b ON k.klant_id = b.klant_id GROUP BY k.klant_id, k.naam ORDER BY totaal DESC LIMIT 1',
            win:'VIP customer found! This is gold for the marketing department. 👑' },
    },
    delete_test_klant: {
      nl: { title:'Testklant verwijderen', who:'Developer',
            story:'Bij de opstart werd een testklant (klant_id=99) aangemaakt. Verwijder die rij.',
            obj:'DELETE FROM klant WHERE klant_id = 99',
            win:'Testdata opgeruimd! De database is nu schoon. 🧹' },
      en: { title:'Delete test customer', who:'Developer',
            story:'During setup a test customer (klant_id=99) was created. Delete that row.',
            obj:'DELETE FROM klant WHERE klant_id = 99',
            win:'Test data cleaned up! The database is now clean. 🧹' },
    },
    join_klant_review: {
      nl: { title:'Klanten met hun reviews', who:'Analytics',
            story:'Welke klanten hebben reviews geschreven? Gebruik een JOIN om namen en reviewscores samen te tonen.',
            obj:'SELECT k.naam, r.score, r.tekst FROM klant k INNER JOIN review r ON k.klant_id = r.klant_id ORDER BY r.score DESC',
            win:'Review-overzicht per klant klaar! Analysts zijn blij. 📋' },
      en: { title:'Customers with their reviews', who:'Analytics',
            story:'Which customers have written reviews? Use a JOIN to show names and review scores together.',
            obj:'SELECT k.naam, r.score, r.tekst FROM klant k INNER JOIN review r ON k.klant_id = r.klant_id ORDER BY r.score DESC',
            win:'Review overview per customer ready! Analysts are happy. 📋' },
    },
    debug_missing_groupby: {
      nl: { title:'🐛 Debug: GROUP BY vergeten', who:'Lena — Developer',
            story:'Lena heeft een query geschreven om de <strong>totale stock per categorie</strong> te berekenen, maar krijgt een fout. Kun jij de bug vinden en repareren?',
            obj:'Herstel de query zodat de stock per categorie gegroepeerd wordt.',
            win:'Bug gevonden! Zonder GROUP BY kan SUM() niet per categorie berekenen. 🐛→✅' },
      en: { title:'🐛 Debug: GROUP BY forgotten', who:'Lena — Developer',
            story:'Lena wrote a query to calculate the <strong>total stock per category</strong> but gets an error. Can you find and fix the bug?',
            obj:'Fix the query so that stock is grouped per category.',
            win:'Bug found! Without GROUP BY, SUM() cannot calculate per category. 🐛→✅' },
    },
    debug_update_no_where: {
      nl: { title:'🐛 Debug: UPDATE zonder WHERE', who:'Alex — Developer',
            story:'Alex stuurde deze UPDATE naar productie en heeft <strong>per ongeluk alle prijzen op €99 gezet</strong>. Repareer de query zodat ze enkel de Ergonomische stoel (product_id=4) aanpast.',
            obj:'Voeg een WHERE-clausule toe zodat enkel product_id = 4 bijgewerkt wordt.',
            win:'Bug gerepareerd! WHERE is verplicht bij UPDATE. Zonder WHERE worden ALLE rijen aangepast. 🛡️' },
      en: { title:'🐛 Debug: UPDATE without WHERE', who:'Alex — Developer',
            story:'Alex sent this UPDATE to production and <strong>accidentally set all prices to €99</strong>. Fix the query so it only updates the Ergonomic Chair (product_id=4).',
            obj:'Add a WHERE clause so that only product_id = 4 is updated.',
            win:'Bug fixed! WHERE is required with UPDATE. Without WHERE ALL rows are updated. 🛡️' },
    },
    debug_having_no_groupby: {
      nl: { title:'🐛 Debug: HAVING zonder GROUP BY', who:'Junior Developer',
            story:'Deze query zou klanten moeten tonen met meer dan 1 bestelling, maar gooit een fout. Repareer hem.',
            obj:'Voeg GROUP BY toe zodat HAVING correct werkt.',
            win:'Bug gevonden! HAVING werkt altijd samen met GROUP BY — zo kun je groepen filteren na aggregatie. 🎯' },
      en: { title:'🐛 Debug: HAVING without GROUP BY', who:'Junior Developer',
            story:'This query should show customers with more than 1 order but throws an error. Fix it.',
            obj:'Add GROUP BY so that HAVING works correctly.',
            win:'Bug found! HAVING always works together with GROUP BY — that\'s how you filter groups after aggregation. 🎯' },
    },
    debug_join_no_on: {
      nl: { title:'🐛 Debug: JOIN zonder ON', who:'Junior Developer',
            story:'Deze JOIN-query mist de verbindingsconditie en geeft een verkeerd resultaat (kruis-product). Repareer hem.',
            obj:'Voeg de ON-clausule toe om klant en bestelling correct te koppelen.',
            win:'Bug gevonden! Zonder ON-conditie krijg je een Cartesisch product — elke rij gecombineerd met elke rij. 🔗' },
      en: { title:'🐛 Debug: JOIN without ON', who:'Junior Developer',
            story:'This JOIN query is missing the join condition and gives a wrong result (cross product). Fix it.',
            obj:'Add the ON clause to correctly link klant and bestelling.',
            win:'Bug found! Without an ON condition you get a Cartesian product — every row combined with every row. 🔗' },
    },
  },

  // ══ CHAPTERS ════════════════════════════════════════════════════
  chapters: {
    0: {
      nl: { title:'🏠 H1: De Startup', cinTitle:'De Startup 🚀', cinCh:'HOOFDSTUK 1',
            lines:[
              { txt:'Gefeliciteerd, <strong>CEO</strong>! Je hebt €50.000 opgehaald. DataShop gaat live. Maar je klantendatabank is een puinhoop.', who:'Thomas — Adviseur' },
              { txt:'Eerste klanten wachten. Elke fout kost <strong>reputatiepunten</strong>.', who:'System' },
              { txt:'Oké. Ik pak dit aan.', who:'CEO — jij' },
            ],
            recap:'Je beheerst nu de basis van SQL: gegevens opvragen, invoegen, bijwerken en verwijderen.',
            nextPreview:'Volgende stap: crisismanagement met UPDATE en DELETE.' },
      en: { title:'🏠 Ch1: The Startup', cinTitle:'The Startup 🚀', cinCh:'CHAPTER 1',
            lines:[
              { txt:'Congratulations, <strong>CEO</strong>! You\'ve raised €50,000. DataShop is going live. But your customer database is a mess.', who:'Thomas — Advisor' },
              { txt:'First customers are waiting. Every mistake costs <strong>reputation points</strong>.', who:'System' },
              { txt:'OK. I\'ll handle this.', who:'CEO — you' },
            ],
            recap:'You now master the basics of SQL: querying, inserting, updating and deleting data.',
            nextPreview:'Next up: crisis management with UPDATE and DELETE.' },
    },
    1: {
      nl: { title:'⚡ H2: Crisis Mode', cinTitle:'Crisis Mode 🚨', cinCh:'HOOFDSTUK 2',
            lines:[
              { txt:'CEO, we hebben een crisis! Een kortingscode van 99% staat actief. <strong>Social media ontploft!</strong>', who:'Ines — PR Manager' },
              { txt:'Reviews over defecte USB-C Hub komen binnen. Webcam al weken uitverkocht.', who:'Klantenservice' },
              { txt:'Ik regel het. Geef me database-toegang.', who:'CEO — jij' },
            ],
            recap:'Je hebt geleerd hoe je crises oplost met SQL: data aanpassen, corrigeren en verwijderen.',
            nextPreview:'Volgende stap: tabellen samenvoegen met JOIN en geavanceerde aggregaten.' },
      en: { title:'⚡ Ch2: Crisis Mode', cinTitle:'Crisis Mode 🚨', cinCh:'CHAPTER 2',
            lines:[
              { txt:'CEO, we have a crisis! A 99% discount code is active. <strong>Social media is exploding!</strong>', who:'Ines — PR Manager' },
              { txt:'Reviews about the defective USB-C Hub are coming in. Webcam out of stock for weeks.', who:'Customer Service' },
              { txt:'I\'ll sort it. Give me database access.', who:'CEO — you' },
            ],
            recap:'You\'ve learned how to resolve crises with SQL: updating, correcting and deleting data.',
            nextPreview:'Next up: joining tables with JOIN and advanced aggregates.' },
    },
    2: {
      nl: { title:'🔗 H3: Data Expert', cinTitle:'Data Expert 🧠', cinCh:'HOOFDSTUK 3',
            lines:[
              { txt:'Investeerders willen rapporten. Welke klanten bestellen het meest? Beste categorieën?', who:'Alex — Data Analyst' },
              { txt:'We willen de database uitbreiden met nieuwe tabellen.', who:'Raad van Bestuur' },
              { txt:'Laat me de queries schrijven.', who:'CEO — jij' },
            ],
            recap:'Je bent nu een data expert: JOINs, aggregaten en DDL behoren tot je toolkit.',
            nextPreview:'Volgende stap: geavanceerde queries met DISTINCT, aliassen en subqueries.' },
      en: { title:'🔗 Ch3: Data Expert', cinTitle:'Data Expert 🧠', cinCh:'CHAPTER 3',
            lines:[
              { txt:'Investors want reports. Which customers order the most? Best categories?', who:'Alex — Data Analyst' },
              { txt:'We want to expand the database with new tables.', who:'Board of Directors' },
              { txt:'Let me write the queries.', who:'CEO — you' },
            ],
            recap:'You are now a data expert: JOINs, aggregates and DDL are all in your toolkit.',
            nextPreview:'Next up: advanced queries with DISTINCT, aliases and subqueries.' },
    },
    3: {
      nl: { title:'🧬 H4: Expert Modus', cinTitle:'Expert Modus 🧬', cinCh:'HOOFDSTUK 4',
            lines:[
              { txt:'Proficiat CEO! Je beheerst de basis volledig. Tijd voor <strong>gevorderde SQL</strong>: DISTINCT, aliassen, subqueries.', who:'AI Systeem' },
              { txt:'We overwegen €500.000 te investeren. We willen rapporten die onze analistensoftware niet aankan. Imponeer ons.', who:'Venture Capitalist' },
              { txt:'Ik schrijf queries die jullie nooit eerder gezien hebben.', who:'CEO — jij' },
            ],
            recap:'Expert-niveau: DISTINCT, aliassen, subqueries en complexe JOIN-combinaties.',
            nextPreview:'Volgende stap: enterprise SQL met INNER/LEFT JOIN, HAVING en DDL.' },
      en: { title:'🧬 Ch4: Expert Mode', cinTitle:'Expert Mode 🧬', cinCh:'CHAPTER 4',
            lines:[
              { txt:'Congratulations CEO! You\'ve fully mastered the basics. Time for <strong>advanced SQL</strong>: DISTINCT, aliases, subqueries.', who:'AI System' },
              { txt:'We\'re considering investing €500,000. We want reports that our analyst software can\'t handle. Impress us.', who:'Venture Capitalist' },
              { txt:'I\'ll write queries you\'ve never seen before.', who:'CEO — you' },
            ],
            recap:'Expert level: DISTINCT, aliases, subqueries and complex JOIN combinations.',
            nextPreview:'Next up: enterprise SQL with INNER/LEFT JOIN, HAVING and DDL.' },
    },
    4: {
      nl: { title:'🏗️ H5: Data Architect', cinTitle:'Data Architect 🏗️', cinCh:'HOOFDSTUK 5',
            lines:[
              { txt:'DataShop expandeert internationaal. We hebben <strong>professionele JOINs, gegroepeerde rapporten en een strakke database-architectuur</strong> nodig.', who:'Boardroom' },
              { txt:'We schakelen over naar ANSI-standaard JOIN-syntax. Schrijf queries die echte databases aankunnen: INNER JOIN, LEFT JOIN, GROUP BY met HAVING, en DDL voor nieuwe structuren.', who:'Lena — Lead Engineer' },
              { txt:'Ik bouw de databank die DataShop naar de beurs brengt.', who:'CEO — jij' },
            ],
            recap:'Je bent nu een volwaardige Data Architect. DataShop is klaar voor de beursgang.',
            nextPreview:'' },
      en: { title:'🏗️ Ch5: Data Architect', cinTitle:'Data Architect 🏗️', cinCh:'CHAPTER 5',
            lines:[
              { txt:'DataShop is expanding internationally. We need <strong>professional JOINs, grouped reports and a solid database architecture</strong>.', who:'Boardroom' },
              { txt:'We\'re switching to ANSI standard JOIN syntax. Write queries that real databases can handle: INNER JOIN, LEFT JOIN, GROUP BY with HAVING, and DDL for new structures.', who:'Lena — Lead Engineer' },
              { txt:'I\'ll build the database that takes DataShop to the stock exchange.', who:'CEO — you' },
            ],
            recap:'You are now a fully-fledged Data Architect. DataShop is ready for its IPO.',
            nextPreview:'' },
    },
  },

  // ══ ACHIEVEMENTS ════════════════════════════════════════════════
  achievements: {
    first_insert:     { nl:{ name:'Eerste INSERT',      desc:'Je eerste rij toegevoegd.' },                  en:{ name:'First INSERT',        desc:'Your first row added.' } },
    first_update:     { nl:{ name:'Data Wijziger',      desc:'Je eerste UPDATE uitgevoerd.' },               en:{ name:'Data Changer',        desc:'Your first UPDATE executed.' } },
    first_delete:     { nl:{ name:'Opruimer',           desc:'Je eerste DELETE uitgevoerd.' },               en:{ name:'Clean-up Crew',       desc:'Your first DELETE executed.' } },
    first_select:     { nl:{ name:'Data Analist',       desc:'Je eerste SELECT uitgevoerd.' },               en:{ name:'Data Analyst',        desc:'Your first SELECT executed.' } },
    ddl_master:       { nl:{ name:'Architect',          desc:'Tabel aangemaakt of gewijzigd.' },             en:{ name:'Architect',           desc:'Table created or modified.' } },
    speed:            { nl:{ name:'Snelheidsdemon',     desc:'Scenario opgelost in < 10 seconden.' },        en:{ name:'Speed Demon',         desc:'Scenario solved in < 10 seconds.' } },
    streak3:          { nl:{ name:'In Vuur en Vlam',    desc:'3 op rij correct.' },                          en:{ name:'On Fire',             desc:'3 in a row correct.' } },
    streak5:          { nl:{ name:'Vulkaan',            desc:'5 op rij correct.' },                          en:{ name:'Volcano',             desc:'5 in a row correct.' } },
    gdpr:             { nl:{ name:'GDPR-held',          desc:'Klant correct gedeactiveerd.' },               en:{ name:'GDPR Hero',           desc:'Customer correctly deactivated.' } },
    join:             { nl:{ name:'JOIN Meester',       desc:'JOIN-query geslaagd.' },                       en:{ name:'JOIN Master',         desc:'JOIN query succeeded.' } },
    agg:              { nl:{ name:'Aggregatie Expert',  desc:'AVG, SUM, MAX of MIN gebruikt.' },             en:{ name:'Aggregation Expert',  desc:'AVG, SUM, MAX or MIN used.' } },
    security:         { nl:{ name:'Beveiligingschef',   desc:'Foute kortingscode gedeactiveerd.' },          en:{ name:'Security Chief',      desc:'Faulty discount code deactivated.' } },
    ch1:              { nl:{ name:'Startup CEO',        desc:'Hoofdstuk 1 voltooid.' },                      en:{ name:'Startup CEO',         desc:'Chapter 1 completed.' } },
    ch2:              { nl:{ name:'Crisis Manager',     desc:'Hoofdstuk 2 voltooid.' },                      en:{ name:'Crisis Manager',      desc:'Chapter 2 completed.' } },
    ch3:              { nl:{ name:'Data Expert',        desc:'Hoofdstuk 3 voltooid.' },                      en:{ name:'Data Expert',         desc:'Chapter 3 completed.' } },
    rep100:           { nl:{ name:'Perfecte CEO',       desc:'Reputatie op 100 gehouden.' },                 en:{ name:'Perfect CEO',         desc:'Reputation kept at 100.' } },
    xp500:            { nl:{ name:'500 XP Elite',       desc:'500 XP bereikt.' },                            en:{ name:'500 XP Elite',        desc:'500 XP reached.' } },
    ch4:              { nl:{ name:'Expert Modus',       desc:'Hoofdstuk 4 voltooid.' },                      en:{ name:'Expert Mode',         desc:'Chapter 4 completed.' } },
    distinct_pro:     { nl:{ name:'DISTINCT Pro',       desc:'DISTINCT query geslaagd.' },                   en:{ name:'DISTINCT Pro',        desc:'DISTINCT query succeeded.' } },
    subquery_pro:     { nl:{ name:'Subquery Tovenaar',  desc:'Subquery in WHERE geslaagd.' },                en:{ name:'Subquery Wizard',     desc:'Subquery in WHERE succeeded.' } },
    alias_pro:        { nl:{ name:'Alias Artiest',      desc:'AS-alias query geslaagd.' },                   en:{ name:'Alias Artist',        desc:'AS alias query succeeded.' } },
    all_done:         { nl:{ name:'Data Legende',       desc:'Alle missies voltooid!' },                     en:{ name:'Data Legend',         desc:'All missions completed!' } },
    ch5:              { nl:{ name:'Data Architect',     desc:'Hoofdstuk 5 voltooid.' },                      en:{ name:'Data Architect',      desc:'Chapter 5 completed.' } },
    inner_join_pro:   { nl:{ name:'JOIN Meester',       desc:'INNER JOIN met ON-syntax geslaagd.' },         en:{ name:'JOIN Master',         desc:'INNER JOIN with ON syntax succeeded.' } },
    left_join_pro:    { nl:{ name:'LEFT JOIN Expert',   desc:'LEFT JOIN met nulls geslaagd.' },              en:{ name:'LEFT JOIN Expert',    desc:'LEFT JOIN with nulls succeeded.' } },
    having_pro:       { nl:{ name:'HAVING Tovenaar',    desc:'GROUP BY + HAVING gecombineerd.' },            en:{ name:'HAVING Wizard',       desc:'GROUP BY + HAVING combined.' } },
    ddl_architect:    { nl:{ name:'Database Architect', desc:'CREATE TABLE én ALTER TABLE uitgevoerd.' },    en:{ name:'Database Architect',  desc:'CREATE TABLE and ALTER TABLE executed.' } },
    xp1000:           { nl:{ name:'1000 XP Legende',   desc:'1000 XP bereikt.' },                           en:{ name:'1000 XP Legend',      desc:'1000 XP reached.' } },
    tut_complete:     { nl:{ name:'Tutorial Meester',   desc:'Alle tutoriallessen voltooid.' },              en:{ name:'Tutorial Master',     desc:'All tutorial lessons completed.' } },
    sql_polyglot:     { nl:{ name:'SQL Polyglot',       desc:'SELECT, INSERT, UPDATE en DELETE gebruikt in missies.' }, en:{ name:'SQL Polyglot', desc:'SELECT, INSERT, UPDATE and DELETE used in missions.' } },
    no_hint_ch1:      { nl:{ name:'Geen hints nodig',   desc:'Hoofdstuk 1 voltooid zonder één hint te gebruiken.' }, en:{ name:'No hints needed', desc:'Chapter 1 completed without using a single hint.' } },
    speedster:        { nl:{ name:'Snelheidsduivel',    desc:'Een missie met 25+ snelheidsbonus voltooid.' }, en:{ name:'Speed Freak',        desc:'A mission completed with 25+ speed bonus.' } },
    rep_recovered:    { nl:{ name:'Comeback',           desc:'Reputatie hersteld van onder 50% naar boven 80%.' }, en:{ name:'Comeback',         desc:'Reputation recovered from below 50% to above 80%.' } },
    like_pro:         { nl:{ name:'Patroonzoeker',      desc:'LIKE-query met wildcard geslaagd.' },          en:{ name:'Pattern Finder',      desc:'LIKE query with wildcard succeeded.' } },
    between_pro:      { nl:{ name:'Bereikfilter',       desc:'BETWEEN-query geslaagd.' },                   en:{ name:'Range Filter',        desc:'BETWEEN query succeeded.' } },
    null_hunter:      { nl:{ name:'NULL Hunter',        desc:'IS NULL query geslaagd.' },                   en:{ name:'NULL Hunter',         desc:'IS NULL query succeeded.' } },
    anti_join_pro:    { nl:{ name:'Anti-Join Expert',   desc:'LEFT JOIN + IS NULL anti-join geslaagd.' },    en:{ name:'Anti-Join Expert',    desc:'LEFT JOIN + IS NULL anti-join succeeded.' } },
    not_in_pro:       { nl:{ name:'NOT IN Specialist',  desc:'NOT IN subquery geslaagd.' },                 en:{ name:'NOT IN Specialist',   desc:'NOT IN subquery succeeded.' } },
    case_when_pro:    { nl:{ name:'Label Artiest',      desc:'CASE WHEN query geslaagd.' },                  en:{ name:'Label Artist',        desc:'CASE WHEN query succeeded.' } },
  },

  // ══ OFFICES ══════════════════════════════════════════════════════
  offices: {
    0:    { nl:{ name:'Thuiskantoor',         desc:'Vanuit je slaapkamer. De droom is groot.' },                          en:{ name:'Home Office',           desc:'From your bedroom. The dream is big.' } },
    150:  { nl:{ name:'Gehuurd Kantoor',      desc:'Een echt kantoor in de stad.' },                                      en:{ name:'Rented Office',         desc:'A real office in the city.' } },
    350:  { nl:{ name:'DataShop HQ',          desc:'10 medewerkers, investeerders kijken toe.' },                         en:{ name:'DataShop HQ',           desc:'10 employees, investors are watching.' } },
    650:  { nl:{ name:'Glazen Wolkenkrabber', desc:'30e verdieping, je bent een succesverhaal.' },                        en:{ name:'Glass Skyscraper',      desc:'30th floor, you are a success story.' } },
    1000: { nl:{ name:'Global DataShop',      desc:'Internationaal bedrijf. Forbes schrijft over jou.' },                 en:{ name:'Global DataShop',       desc:'International company. Forbes writes about you.' } },
    1500: { nl:{ name:'DataShop Universe',    desc:'Jij bent de standaard. Harvard doceert over jou.' },                 en:{ name:'DataShop Universe',     desc:'You are the standard. Harvard lectures about you.' } },
  },

  // ══ RANKS ═══════════════════════════════════════════════════════
  ranks: {
    0:    { nl:'Startup CEO',                 en:'Startup CEO' },
    150:  { nl:'Junior Data Analist',         en:'Junior Data Analyst' },
    350:  { nl:'SQL Specialist',              en:'SQL Specialist' },
    650:  { nl:'Senior Data Engineer',        en:'Senior Data Engineer' },
    1000: { nl:'Chief Data Officer',          en:'Chief Data Officer' },
    1500: { nl:'Data Architect — Legende',    en:'Data Architect — Legend' },
  },

  // ══ CONCEPT INTROS ═══════════════════════════════════════════════
  concepts: {
    select: {
      nl:{ title:'SELECT — Gegevens opvragen',
           body:'Met <strong>SELECT</strong> haal je rijen op uit een tabel. De basisvorm is:<br><code>SELECT kolom1, kolom2 FROM tabel WHERE conditie</code><br>Gebruik <code>*</code> voor alle kolommen.',
           tip:'De volgorde is altijd: SELECT → FROM → WHERE → ORDER BY → LIMIT' },
      en:{ title:'SELECT — Querying data',
           body:'With <strong>SELECT</strong> you retrieve rows from a table. The basic form is:<br><code>SELECT column1, column2 FROM table WHERE condition</code><br>Use <code>*</code> for all columns.',
           tip:'The order is always: SELECT → FROM → WHERE → ORDER BY → LIMIT' },
    },
    insert: {
      nl:{ title:'INSERT — Nieuwe rij toevoegen',
           body:'Met <strong>INSERT INTO</strong> voeg je een nieuwe rij toe.<br><code>INSERT INTO tabel (kolom1, kolom2) VALUES (waarde1, waarde2)</code><br>Tekst staat altijd tussen enkele aanhalingstekens.',
           tip:'Vermeld de kolomnamen expliciet — dan hoef je de volgorde in de tabel niet te kennen.' },
      en:{ title:'INSERT — Adding a new row',
           body:'With <strong>INSERT INTO</strong> you add a new row.<br><code>INSERT INTO table (column1, column2) VALUES (value1, value2)</code><br>Text always goes between single quotes.',
           tip:'State the column names explicitly — then you don\'t need to know the order in the table.' },
    },
    update: {
      nl:{ title:'UPDATE — Bestaande rij wijzigen',
           body:'Met <strong>UPDATE … SET … WHERE</strong> pas je bestaande rijen aan.<br><code>UPDATE tabel SET kolom = nieuwewaarde WHERE conditie</code>',
           tip:'⚠️ Altijd WHERE gebruiken! Zonder WHERE pas je ALLE rijen tegelijk aan.' },
      en:{ title:'UPDATE — Modifying an existing row',
           body:'With <strong>UPDATE … SET … WHERE</strong> you modify existing rows.<br><code>UPDATE table SET column = newvalue WHERE condition</code>',
           tip:'⚠️ Always use WHERE! Without WHERE you update ALL rows at once.' },
    },
    delete: {
      nl:{ title:'DELETE — Rij(en) verwijderen',
           body:'Met <strong>DELETE FROM … WHERE</strong> verwijder je rijen.<br><code>DELETE FROM tabel WHERE conditie</code>',
           tip:'⚠️ DELETE is onomkeerbaar. Overweeg UPDATE SET actief = 0 als alternatief.' },
      en:{ title:'DELETE — Removing row(s)',
           body:'With <strong>DELETE FROM … WHERE</strong> you remove rows.<br><code>DELETE FROM table WHERE condition</code>',
           tip:'⚠️ DELETE is irreversible. Consider UPDATE SET actief = 0 as an alternative.' },
    },
    ddl: {
      nl:{ title:'DDL — Database structuur aanpassen',
           body:'DDL-commando\'s (Data Definition Language) wijzigen de <em>structuur</em> van de database.<br><code>CREATE TABLE naam (kolom datatype, ...)</code><br><code>ALTER TABLE naam ADD COLUMN kolom datatype</code>',
           tip:'Bestaande rijen krijgen automatisch NULL voor een nieuwe kolom via ALTER TABLE.' },
      en:{ title:'DDL — Modifying database structure',
           body:'DDL commands (Data Definition Language) change the <em>structure</em> of the database.<br><code>CREATE TABLE name (column datatype, ...)</code><br><code>ALTER TABLE name ADD COLUMN column datatype</code>',
           tip:'Existing rows automatically get NULL for a new column via ALTER TABLE.' },
    },
    like: {
      nl:{ title:'LIKE — Zoeken op patroon',
           body:'Met <strong>LIKE</strong> filter je op een tekstpatroon.<br><code>WHERE naam LIKE \'%Jan%\'</code> — bevat "Jan"<br><code>WHERE naam LIKE \'J%\'</code> — begint met J',
           tip:'% staat voor nul of meer willekeurige tekens. _ staat voor precies één teken.' },
      en:{ title:'LIKE — Searching by pattern',
           body:'With <strong>LIKE</strong> you filter by a text pattern.<br><code>WHERE naam LIKE \'%Jan%\'</code> — contains "Jan"<br><code>WHERE naam LIKE \'J%\'</code> — starts with J',
           tip:'% represents zero or more characters. _ represents exactly one character.' },
    },
    between: {
      nl:{ title:'BETWEEN — Bereikfilter',
           body:'Met <strong>BETWEEN a AND b</strong> filter je op een bereik — inclusief de grenzen zelf.<br><code>WHERE prijs BETWEEN 10 AND 50</code>',
           tip:'BETWEEN a AND b is gelijk aan: WHERE kolom >= a AND kolom <= b' },
      en:{ title:'BETWEEN — Range filter',
           body:'With <strong>BETWEEN a AND b</strong> you filter by a range — including the boundaries.<br><code>WHERE prijs BETWEEN 10 AND 50</code>',
           tip:'BETWEEN a AND b is equivalent to: WHERE column >= a AND column <= b' },
    },
    isnull: {
      nl:{ title:'IS NULL — Ontbrekende waarden',
           body:'NULL is de <em>afwezigheid</em> van een waarde. Je kan er NIET op vergelijken met =.<br><code>WHERE kolom IS NULL</code> — geen waarde ingevuld<br>❌ <code>WHERE kolom = NULL</code> werkt nooit!',
           tip:'Anti-join: LEFT JOIN + WHERE rechtertabel.id IS NULL → vindt rijen die NIET in de rechtertabel staan.' },
      en:{ title:'IS NULL — Missing values',
           body:'NULL is the <em>absence</em> of a value. You CANNOT compare it with =.<br><code>WHERE column IS NULL</code> — no value filled in<br>❌ <code>WHERE column = NULL</code> never works!',
           tip:'Anti-join: LEFT JOIN + WHERE righttable.id IS NULL → finds rows NOT in the right table.' },
    },
    casewhen: {
      nl:{ title:'CASE WHEN — Conditionele labels',
           body:'Met <strong>CASE WHEN</strong> maak je een nieuwe kolom op basis van condities.<br><code>CASE WHEN stock = 0 THEN \'Uitverkocht\' WHEN stock &lt; 5 THEN \'Bijna op\' ELSE \'Op voorraad\' END AS status</code>',
           tip:'Sluit altijd af met END. Geef de kolom een naam via AS.' },
      en:{ title:'CASE WHEN — Conditional labels',
           body:'With <strong>CASE WHEN</strong> you create a new column based on conditions.<br><code>CASE WHEN stock = 0 THEN \'Out of stock\' WHEN stock &lt; 5 THEN \'Low\' ELSE \'In stock\' END AS status</code>',
           tip:'Always end with END. Give the column a name via AS.' },
    },
  },
};

// ── NARRATIVE ACCESSOR ────────────────────────────────────────────
// n('new_customer', 'title')   → scenario title in current lang
// n('new_customer', 'story')   → scenario story in current lang
// nCh(0, 'title')              → chapter title in current lang
// nAch('first_insert', 'name') → achievement name in current lang
// nRank(350)                   → rank title in current lang
// nOffice(350, 'name')         → office name in current lang
// nConcept('select', 'body')   → concept body in current lang

function n(id, field) {
  const entry = NARRATIVE.scenarios[id];
  if (!entry) return '';
  const lang = (LANG === 'en' && entry.en) ? 'en' : 'nl';
  return entry[lang]?.[field] ?? entry.nl?.[field] ?? '';
}

function nCh(id, field) {
  const entry = NARRATIVE.chapters[id];
  if (!entry) return '';
  const lang = (LANG === 'en' && entry.en) ? 'en' : 'nl';
  return entry[lang]?.[field] ?? entry.nl?.[field] ?? '';
}

function nAch(id, field) {
  const entry = NARRATIVE.achievements[id];
  if (!entry) return '';
  const lang = (LANG === 'en' && entry.en) ? 'en' : 'nl';
  return entry[lang]?.[field] ?? entry.nl?.[field] ?? '';
}

function nRank(min) {
  const entry = NARRATIVE.ranks[min];
  if (!entry) return '';
  return (LANG === 'en' ? entry.en : entry.nl) ?? entry.nl ?? '';
}

function nOffice(min, field) {
  const entry = NARRATIVE.offices[min];
  if (!entry) return '';
  const lang = (LANG === 'en' && entry.en) ? 'en' : 'nl';
  return entry[lang]?.[field] ?? entry.nl?.[field] ?? '';
}

function nConcept(type, field) {
  const entry = NARRATIVE.concepts[type];
  if (!entry) return '';
  const lang = (LANG === 'en' && entry.en) ? 'en' : 'nl';
  return entry[lang]?.[field] ?? entry.nl?.[field] ?? '';
}
